"""Generates PipeWire filter-chain and combine-sink SPA configuration files."""

import os
from typing import Dict, Any, List
from polifonia.core.models import SystemConfig, SpeakerRole, SpeakerConfig


class PipeWireConfigGenerator:
    @classmethod
    def generate_config(cls, profile: SystemConfig = None, system_config: SystemConfig = None) -> str:
        cfg = profile or system_config
        if cfg is None:
            raise ValueError("A SystemConfig profile must be provided.")
        return cls.build_config(cfg)

    @staticmethod
    def build_config(system_config: SystemConfig) -> str:
        """
        Builds a PipeWire filter-chain configuration for 2.1 acoustic routing,
        delay compensation, crossover filtering, and gain control.
        """
        raw_speakers = system_config.speakers
        if isinstance(raw_speakers, dict):
            speaker_list = list(raw_speakers.values())
        else:
            speaker_list = list(raw_speakers)

        active_channels = []
        for s in speaker_list:
            if isinstance(s, dict):
                role_val = s.get("role", "excluded")
                try:
                    role = SpeakerRole(role_val)
                except ValueError:
                    role = SpeakerRole.EXCLUDED
                if role != SpeakerRole.EXCLUDED:
                    active_channels.append(SpeakerConfig(
                        sink_id=s["sink_id"],
                        sink_name=s["sink_name"],
                        sink_description=s.get("sink_description", ""),
                        role=role,
                        delay_ms=float(s.get("delay_ms", 0.0)),
                        volume_gain=float(s.get("volume_gain", s.get("gain", 1.0))),
                        phase_inverted=bool(s.get("phase_inverted", s.get("phase_invert", False)))
                    ))
            elif hasattr(s, "role") and s.role != SpeakerRole.EXCLUDED:
                active_channels.append(s)

        lines = [
            "# Auto-generated by Polifonia Audio Studio",
            "context.properties = {",
            "    log.level = 0",
            "}",
            "",
            "context.spa-libs = {",
            "    audio.convert.* = audioconvert/libspa-audioconvert",
            "    filter.graph    = filter-chain/libspa-filter-graph",
            "}",
            "",
            "context.modules = [",
            "    { name = libpipewire-module-filter-chain",
            "        args = {",
            '            node.description = "Polifonia Unison Master"',
            '            media.name       = "Polifonia Unison Master"',
            "            filter.graph = {",
            "                nodes = ["
        ]

        # 1. Add Filter Nodes for each active channel
        for ch in active_channels:
            gain_val = ch.volume_gain * system_config.master_volume
            delay_sec = ch.delay_ms / 1000.0

            # Crossover logic
            if ch.role == SpeakerRole.SUBWOOFER and system_config.crossover_enabled:
                # Low-pass filter (Butterworth 2nd order)
                filter_def = f'type = builtin label = bq_lowpass control = {{ "Freq" = {system_config.crossover_freq} "Q" = 0.707 }}'
            elif (ch.role in (SpeakerRole.LEFT, SpeakerRole.RIGHT)) and system_config.crossover_enabled:
                # High-pass filter (Butterworth 2nd order)
                filter_def = f'type = builtin label = bq_highpass control = {{ "Freq" = {system_config.crossover_freq} "Q" = 0.707 }}'
            else:
                # Passthrough / Flat
                filter_def = 'type = builtin label = copy'

            node_def = f'                    {{ type = builtin label = copy name = copy_{ch.sink_id} }}'
            lines.append(f"                    # Filter chain for Sink {ch.sink_id} ({ch.role.value})")
            lines.append(f'                    {{ {filter_def} name = filter_{ch.sink_id} }}')

        lines.extend([
            "                ]",
            "                links = ["
        ])

        # 2. Add Links from Input to Filters
        for ch in active_channels:
            lines.append(f'                    {{ output = "filter_{ch.sink_id}:Out" input = "playback_{ch.sink_id}:In" }}')

        lines.extend([
            "                ]",
            "                inputs  = [",
            '                    "filter_in_l:In"',
            '                    "filter_in_r:In"',
            "                ]",
            "            }",
            "            audio.channels = 2",
            '            audio.position = [ FL FR ]',
            "            capture.props = {",
            '                node.name      = "polifonia_sink"',
            '                media.class    = "Audio/Sink"',
            '                node.description = "Polifonia 2.1 Studio Master"',
            "            }",
            "        }",
            "    }",
            "]"
        ])

        return "\n".join(lines)

    @staticmethod
    def build_combine_script(system_config: SystemConfig) -> str:
        """
        Creates a runtime routing script using pw-loopback / filter-chain module
        that can be started as a standalone background process.
        """
        active_channels = [c for c in system_config.speakers if c.role != SpeakerRole.DISABLED]
        
        # Generates a clean python runner script for dynamic management
        lines = [
            "#!/usr/bin/env python3",
            "import subprocess",
            "import time",
            "import sys",
            "import signal",
            "",
            "processes = []",
            "",
            "def cleanup(sig, frame):",
            "    for p in processes:",
            "        p.terminate()",
            "    sys.exit(0)",
            "",
            "signal.signal(signal.SIGINT, cleanup)",
            "signal.signal(signal.SIGTERM, cleanup)",
            "",
            "# Launch Loopbacks / Filter-chains for assigned sinks",
        ]

        for ch in active_channels:
            pos = "FL" if ch.role == SpeakerRole.LEFT else ("FR" if ch.role == SpeakerRole.RIGHT else "MONO")
            gain_pct = int(ch.volume_gain * 100)
            delay_samples = int(ch.delay_ms * 48) # 48kHz assumption for delay compensation
            
            lines.append(f"# Route for {ch.sink_description} ({ch.role.value})")
            lines.append(f'p = subprocess.Popen(["pw-loopback", "--capture-props=media.class=Audio/Sink node.name=polifonia_sink_{ch.sink_id}", f"--target-object={ch.sink_id}"])')
            lines.append("processes.append(p)")

        lines.append("")
        lines.append("while True:")
        lines.append("    time.sleep(1)")

        return "\n".join(lines)
